title: Configuration
data:
  phone: '(304) 292-0905'
  business_hours: |-
    Monday - Friday:<br/> 8 am – 4:00 pm<br/><br/>
    Saturday and Sunday:<br/> Closed<br/>
  address: |-
    141 Brookhaven Road<br/>
    Morgantown, WV 26508
  employment_opportunities:
    - 'Heavy Equipment Operators'
    - 'CDL Truck Drivers'
    - 'Paving Operators / Laborers'
  404_title: '404 Error'
  404_text: 'We''re sorry, this page doesn''t exist.'
