title: Configuration
data:
  phone: '(304) 292-0905'
  business_hours: |-
    Monday - Friday:<br/> 8 am – 4:00 pm<br/><br/>
    Saturday and Sunday:<br/> Closed<br/>
  address: |-
    141 Brookhaven Road<br/>
    Morgantown, WV 26508
  employment_opportunities:
    - 'Heavy Equipment Operators'
    - 'CDL Truck Drivers'
    - 'Paving Operators / Laborers'
  directions_url: 'https://www.google.com/maps/dir/39.6155521,-79.9304626/parrotta+paving/@39.6178136,-79.9328575,15z/data=!4m9!4m8!1m1!4e1!1m5!1m1!1s0x88357b87b40bfbcb:0x55a42f79d8221361!2m2!1d-79.9154438!2d39.6103298'
  404_title: '404 Error'
  404_text: 'We''re sorry, this page doesn''t exist.'
